// Builds src/data/words.js from the an-array-of-english-words package.
// Keeps 3–8 letter lowercase a–z words so Word Grid stays a small download.
import { writeFileSync } from "node:fs";
import { createRequire } from "node:module";
const words = createRequire(import.meta.url)("an-array-of-english-words");
const keep = words.filter((w) => /^[a-z]{3,8}$/.test(w));
writeFileSync(
  new URL("../src/data/words.js", import.meta.url),
  `// Generated by scripts/build-words.mjs — ${keep.length} words, 3–8 letters.\nexport default ${JSON.stringify(keep.join(" "))};\n`
);
console.log(`wrote ${keep.length} words`);
